<a href="https://colab.research.google.com/github/reyan3/Cgc_training_projects/blob/main/Project_2_Data_Cleaning_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [ ]:
'''CLEANING THE DATASET'''
# df = pd.read_excel("/content/drive/MyDrive/Car_Sales_Dashboard.xlsx" , sheet_name="SalesData")
'''Missing Values'''
# df["STATE"] = df["STATE"].fillna("N/A")
# df["POSTALCODE"] = df["POSTALCODE"].fillna("Unknown")
# print(df.isnull().sum())
'''Droping Duplicates'''
# df.drop_duplicates(inplace=True)
# print(df.duplicated().sum())
'''Rows Datatypes'''
# print(df.info())
'''Unique Values'''
# print(df["sales_rep_fullName"].unique())
'''Invalid Numeric Values'''
# print(df[df["REVENUE"] <= 0])
'''Max and Min Orderdate if abnormality present or not'''
# print(df["ORDERDATE"].min(),
# df["ORDERDATE"].max())
'''Country and Territory check'''
# print(df.groupby("COUNTRY")["TERRITORY"].unique())
'''Consistency in Column Name'''
# df.columns = df.columns.str.strip().str.upper()
'''Saving the Cleaned Dataset'''
# df.to_csv("Car_Sales_Cleaned.csv", index=False)

In [3]:
file_pth = "/content/drive/MyDrive/Car_Sales_Cleaned.csv"
df = pd.read_csv(file_pth)

,ORDER_NUMBER,QUANTITYORDERED,PRICEEACH,REVENUE,ORDERDATE,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,CUSTOMER,ADDRESS,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,SALES_REP_LASTNAME,SALES_REP_FIRSTNAME,SALES_REP_FULLNAME
0,10100,30,100.00,3000.00,2019-01-06,1,1,2019,Vintage Cars,Online Diecast Creations Co.,2304 Long Airport Avenue,Nashua,NH,62005,USA,North America,Young,Valarie,Valarie Young
1,10101,46,53.76,2472.96,2019-01-09,1,1,2019,Vintage Cars,"Blauer See Auto, Co.",Lyonerstr. 34,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Roland Keitel
2,10102,39,100.00,3900.00,2019-01-10,1,1,2019,Vintage Cars,Vitachrome Inc.,2678 Kingston Rd.,NYC,NY,10022,USA,North America,Frick,Michael,Michael Frick
3,10103,42,100.00,4200.00,2019-01-29,1,1,2019,Classic Cars,Baane Mini Imports,Erling Skakkes gate 78,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Jonas Bergulfsen
4,10104,34,100.00,3400.00,2019-01-31,1,1,2019,Classic Cars,Euro Shopping Channel,"C/ Moralzarzal, 86",Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Diego Freyre

**Q1: Which product line generates the highest total sales revenue?**

In [4]:
df.groupby("PRODUCTLINE")["REVENUE"].sum().sort_values(ascending=False)

PRODUCTLINE
Classic Cars        135417.61
Vintage Cars         57806.79
Motorcycles          48295.28
Trucks and Buses     41194.16
Planes               24451.10
Ships                24340.00
Trains               12637.36
Name: REVENUE, dtype: float64

**Q2: Which geographical territory contributes the most sales?**

In [5]:
df.groupby("TERRITORY")["REVENUE"].sum().sort_values(ascending=False)

TERRITORY
EMEA             177616.54
North America    125835.73
APAC              29959.23
Japan             10730.80
Name: REVENUE, dtype: float64

**Q3: Which country has the highest sales volume?**

In [6]:
df.groupby("COUNTRY")["REVENUE"].sum().sort_values(ascending=False)

COUNTRY
USA            117635.73
Spain           57205.42
France          31995.88
Australia       21449.35
Norway          16093.44
Italy           14581.64
Sweden          13831.00
UK              12187.74
Austria          9300.00
India            8509.88
Canada           8200.00
Finland          6800.00
Denmark          6600.00
Philippines      6546.80
Germany          5672.96
Singapore        4184.00
Belgium          3348.46
Name: REVENUE, dtype: float64

**Q4: What is the average order value by product line?**

In [7]:
df.groupby("PRODUCTLINE")["REVENUE"].mean().sort_values(ascending=False)

PRODUCTLINE
Ships               3477.142857
Classic Cars        3472.246410
Trucks and Buses    3432.846667
Motorcycles         2840.898824
Planes              2716.788889
Vintage Cars        2627.581364
Trains              2527.472000
Name: REVENUE, dtype: float64

**Q5: Are sales increasing or decreasing over time?**

In [9]:
monthly_sales = df.groupby(["YEAR_ID","MONTH_ID"])["REVENUE"].sum()
monthly_sales

YEAR_ID  MONTH_ID
2019     1            16972.96
         2             8139.64
         3            18263.70
         4            19623.70
         5            20361.17
         6            20103.87
         7            28174.54
         8            14730.09
         9            17841.70
         10           47373.26
         11          100931.70
         12           31625.97
Name: REVENUE, dtype: float64

**Q6: Which customers generate the highest revenue?**

In [10]:
df.groupby("CUSTOMER")["REVENUE"].sum().sort_values(ascending=False).head(10)

CUSTOMER
Euro Shopping Channel           34426.67
Corporate Gift Ideas Co.        12242.26
Scandinavian Gift Ideas         11531.00
CAF Imports                     10511.00
Diecast Collectables             9902.51
L'ordine Souveniers              9700.00
Mini Gifts Distributors Ltd.     9357.94
Anna's Decorations, Ltd          8800.00
Classic Legends Inc.             7900.00
Norway Gifts By Mail, Co.        7300.00
Name: REVENUE, dtype: float64

**Q7: Which year recorded the highest sales?**

In [11]:
df.groupby("YEAR_ID")["REVENUE"].sum()

YEAR_ID
2019    344142.3
Name: REVENUE, dtype: float64

**Q8: Which months generate the highest revenue?**

In [12]:
df.groupby("MONTH_ID")["REVENUE"].sum().sort_values(ascending=False)

MONTH_ID
11    100931.70
10     47373.26
12     31625.97
7      28174.54
5      20361.17
6      20103.87
4      19623.70
3      18263.70
9      17841.70
1      16972.96
8      14730.09
2       8139.64
Name: REVENUE, dtype: float64

**Q9: Which quarter contributes the highest sales?**

In [14]:
df.groupby("QTR_ID")["REVENUE"].sum().sort_values(ascending=False)

QTR_ID
4    179930.93
3     60746.33
2     60088.74
1     43376.30
Name: REVENUE, dtype: float64

**Q10: Which cities generate the highest revenue?**

In [17]:
df.groupby("CITY")["REVENUE"].sum().sort_values(ascending=False)

CITY
Madrid            47732.94
NYC               18158.00
San Francisco     16810.80
Boras             11531.00
Boston             9902.51
Philadelphia       9800.00
Reggio Emilia      9700.00
San Rafael         9357.94
North Sydney       8800.00
Paris              8144.78
Oslo               7300.00
Nantes             7200.00
Reims              7146.10
Melbourne          6668.00
Makati City        6546.80
London             6500.00
South Brisbane     5981.35
New Bedford        5946.19
Barcelona          5772.48
Manchester         5687.74
Nashua             5583.34
Kolkata            5509.88
Glendale           5505.48
Brickhaven         5304.77
White Plains       4900.00
Bergamo            4881.64
New Haven          4720.00
Graz               4700.00
Vancouver          4700.00
Salzburg           4600.00
Bergen             4593.44
Espoo              4400.00
Las Vegas          4200.00
Bridgewater        4200.00
Stavern            4200.00
Singapore          4184.00
Toulouse           4100.00
Lyon               3800.00
Kobenhavn          3800.00
Pasadena           3746.70
Sevilla            3700.00
Burlingame         3700.00
Los Angeles        3500.00
Montreal           3500.00
Charleroi          3348.46
Koln               3200.00
Mumbai             3000.00
Aaarhus            2800.00
Frankfurt          2472.96
Oulu               2400.00
Brisbane           2300.00
Lule               2300.00
Lille              1605.00
Name: REVENUE, dtype: float64